
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for node1, local, node2

TASK [../roles/nginx : Create nginx group info.] *******************************
ok: [local]
fatal: [node2]: FAILED! => {"changed": false, "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "nginx"}
fatal: [node1]: FAILED! => {"changed": false, "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "nginx"}

TASK [../roles/nginx : Create user.] *******************************************
ok: [local]

TASK [../roles/nginx : Check docker install.] **********************************
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local

TASK [../roles/nginx : Start Nginx load balancer] ******************************
changed: [local]

PLAY RECAP *********************************************************************
local                      : ok=7    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for node1, local, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [local]
ok: [node1]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Start Nginx load balancer] ******************************
changed: [local]
fatal: [node2]: FAILED! => {"changed": false, "msg": "Error starting container 3ef885a062a930507c8f9e2db3a029d81bed0cff416f900fc5ce8d620b48da7a: 400 Client Error for http+docker://localhost/v1.42/containers/3ef885a062a930507c8f9e2db3a029d81bed0cff416f900fc5ce8d620b48da7a/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
fatal: [node1]: FAILED! => {"changed": false, "msg": "Error starting container 3bbaf4ea0554d03f76ffd5e6e950d043873a8f8acc32dd50f66309e9f9b477a7: 400 Client Error for http+docker://localhost/v1.42/containers/3bbaf4ea0554d03f76ffd5e6e950d043873a8f8acc32dd50f66309e9f9b477a7/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}

PLAY RECAP *********************************************************************
local                      : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy a "sudoers" file on the remote machine for editing] ***
changed: [local] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/config'
failed: [node2] (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf) => {"ansible_loop_var": "item", "changed": false, "item": "/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf", "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.1020255-485762-10152452760473/AnsiballZ_copy.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.1020255-485762-10152452760473/AnsiballZ_copy.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.1020255-485762-10152452760473/AnsiballZ_copy.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.copy', init_globals=dict(_module_fqn='ansible.modules.copy', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_1l12aqs5/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 826, in <module>\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_1l12aqs5/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 621, in main\r\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\r\n    mkdir(name, mode)\r\nPermissionError: [Errno 13] Permission denied: b'/config'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/config'
failed: [node1] (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf) => {"ansible_loop_var": "item", "changed": false, "item": "/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf", "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.1046457-485760-246102602685484/AnsiballZ_copy.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.1046457-485760-246102602685484/AnsiballZ_copy.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.1046457-485760-246102602685484/AnsiballZ_copy.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.copy', init_globals=dict(_module_fqn='ansible.modules.copy', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_fc5y4bv7/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 826, in <module>\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_fc5y4bv7/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 621, in main\r\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\r\n    mkdir(name, mode)\r\nPermissionError: [Errno 13] Permission denied: b'/config'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
changed: [local] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/config'
failed: [node2] (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf) => {"ansible_loop_var": "item", "changed": false, "item": "/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf", "module_stderr": "Shared connection to 192.168.134.132 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.3795602-485762-183007649199497/AnsiballZ_copy.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.3795602-485762-183007649199497/AnsiballZ_copy.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.3795602-485762-183007649199497/AnsiballZ_copy.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.copy', init_globals=dict(_module_fqn='ansible.modules.copy', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_5vo4if_9/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 826, in <module>\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_5vo4if_9/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 621, in main\r\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\r\n    mkdir(name, mode)\r\nPermissionError: [Errno 13] Permission denied: b'/config'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/config'
failed: [node1] (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf) => {"ansible_loop_var": "item", "changed": false, "item": "/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf", "module_stderr": "Shared connection to 192.168.134.131 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.4095829-485760-223132619873247/AnsiballZ_copy.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.4095829-485760-223132619873247/AnsiballZ_copy.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1684263018.4095829-485760-223132619873247/AnsiballZ_copy.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.copy', init_globals=dict(_module_fqn='ansible.modules.copy', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_08nn56a4/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 826, in <module>\r\n  File \"/tmp/ansible_ansible.legacy.copy_payload_08nn56a4/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 621, in main\r\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\r\n    mkdir(name, mode)\r\nPermissionError: [Errno 13] Permission denied: b'/config'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

TASK [../roles/nginx : Start Nginx load balancer] ******************************
changed: [local]

PLAY RECAP *********************************************************************
local                      : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [local]
ok: [node2]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for node1, local, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy a "sudoers" file on the remote machine for editing] ***
ok: [local] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
changed: [node2] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
changed: [node1] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
ok: [local] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)
changed: [node1] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)
changed: [node2] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)

TASK [../roles/nginx : Start Nginx load balancer] ******************************
fatal: [node2]: FAILED! => {"changed": false, "msg": "Error starting container 134e3b2b5ca86fbaf36cca0ba96dc1ec52844cc0d2b8106ea3a412c78cee9571: 400 Client Error for http+docker://localhost/v1.42/containers/134e3b2b5ca86fbaf36cca0ba96dc1ec52844cc0d2b8106ea3a412c78cee9571/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
fatal: [node1]: FAILED! => {"changed": false, "msg": "Error starting container 211af008d2d587aa9eeb1f14135ac5e82a33ecbd0c627d484edbe3bcf0dd13fc: 400 Client Error for http+docker://localhost/v1.42/containers/211af008d2d587aa9eeb1f14135ac5e82a33ecbd0c627d484edbe3bcf0dd13fc/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
changed: [local]

PLAY RECAP *********************************************************************
local                      : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy a "sudoers" file on the remote machine for editing] ***
ok: [local] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
ok: [node1] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
ok: [node2] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/api.conf)
ok: [local] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)
ok: [node1] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)
ok: [node2] => (item=/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files/webserver.conf)

TASK [../roles/nginx : Start Nginx load balancer] ******************************
fatal: [node1]: FAILED! => {"changed": false, "msg": "Error starting container 211af008d2d587aa9eeb1f14135ac5e82a33ecbd0c627d484edbe3bcf0dd13fc: 400 Client Error for http+docker://localhost/v1.42/containers/211af008d2d587aa9eeb1f14135ac5e82a33ecbd0c627d484edbe3bcf0dd13fc/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
fatal: [node2]: FAILED! => {"changed": false, "msg": "Error starting container 134e3b2b5ca86fbaf36cca0ba96dc1ec52844cc0d2b8106ea3a412c78cee9571: 400 Client Error for http+docker://localhost/v1.42/containers/134e3b2b5ca86fbaf36cca0ba96dc1ec52844cc0d2b8106ea3a412c78cee9571/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
changed: [local]

PLAY RECAP *********************************************************************
local                      : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
node1                      : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for node1, local, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy a "sudoers" file on the remote machine for editing] ***
failed: [local] (item=node1) => {"ansible_loop_var": "item", "changed": false, "checksum": "3b2fb0a0233b5d3d54b2ec9f0abb01feb1a6684f", "item": "node1", "msg": "Unsupported parameters for (ansible.legacy.copy) module: delegate_to. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr)."}
failed: [node2] (item=node1) => {"ansible_loop_var": "item", "changed": false, "checksum": "3b2fb0a0233b5d3d54b2ec9f0abb01feb1a6684f", "item": "node1", "msg": "Unsupported parameters for (ansible.legacy.copy) module: delegate_to. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr)."}
failed: [node1] (item=node1) => {"ansible_loop_var": "item", "changed": false, "checksum": "3b2fb0a0233b5d3d54b2ec9f0abb01feb1a6684f", "item": "node1", "msg": "Unsupported parameters for (ansible.legacy.copy) module: delegate_to. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr)."}
failed: [local] (item=node2) => {"ansible_loop_var": "item", "changed": false, "checksum": "3b2fb0a0233b5d3d54b2ec9f0abb01feb1a6684f", "item": "node2", "msg": "Unsupported parameters for (ansible.legacy.copy) module: delegate_to. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr)."}
failed: [node1] (item=node2) => {"ansible_loop_var": "item", "changed": false, "checksum": "3b2fb0a0233b5d3d54b2ec9f0abb01feb1a6684f", "item": "node2", "msg": "Unsupported parameters for (ansible.legacy.copy) module: delegate_to. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr)."}
failed: [node2] (item=node2) => {"ansible_loop_var": "item", "changed": false, "checksum": "3b2fb0a0233b5d3d54b2ec9f0abb01feb1a6684f", "item": "node2", "msg": "Unsupported parameters for (ansible.legacy.copy) module: delegate_to. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr)."}

PLAY RECAP *********************************************************************
local                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for node1, local, node2

TASK [../roles/nginx : Copy a "sudoers" file on the remote machine for editing] ***
changed: [local] => (item=node1)
ok: [local] => (item=node2)
failed: [node2 -> local] (item=node1) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node2:/config/nginx/", "item": "node1", "msg": "ssh: Could not resolve hostname node2: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}
failed: [node1 -> local] (item=node1) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node1:/config/nginx/", "item": "node1", "msg": "ssh: Could not resolve hostname node1: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}
failed: [node1 -> local] (item=node2) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node1:/config/nginx/", "item": "node2", "msg": "ssh: Could not resolve hostname node1: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.3]\n", "rc": 12}
failed: [node2 -> local] (item=node2) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node2:/config/nginx/", "item": "node2", "msg": "ssh: Could not resolve hostname node2: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.3]\n", "rc": 12}

TASK [../roles/nginx : Start Nginx load balancer] ******************************
fatal: [local]: FAILED! => {"changed": false, "msg": "Error starting container 5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156: 400 Client Error for http+docker://localhost/v1.42/containers/5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/nginx/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/nginx/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}

PLAY RECAP *********************************************************************
local                      : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy config file to dirs on host] ***********************
fatal: [local]: FAILED! => {"msg": "The conditional check 'ansible_hostname == local' failed. The error was: error while evaluating conditional (ansible_hostname == local): 'local' is undefined. 'local' is undefined\n\nThe error appears to be in '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy config file to dirs on host\n  ^ here\n"}
fatal: [node2]: FAILED! => {"msg": "The conditional check 'ansible_hostname == local' failed. The error was: error while evaluating conditional (ansible_hostname == local): 'local' is undefined. 'local' is undefined\n\nThe error appears to be in '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy config file to dirs on host\n  ^ here\n"}
fatal: [node1]: FAILED! => {"msg": "The conditional check 'ansible_hostname == local' failed. The error was: error while evaluating conditional (ansible_hostname == local): 'local' is undefined. 'local' is undefined\n\nThe error appears to be in '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy config file to dirs on host\n  ^ here\n"}

PLAY RECAP *********************************************************************
local                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for node1, local, node2

TASK [../roles/nginx : Copy config file to dirs on host] ***********************
skipping: [local]
skipping: [node1]
skipping: [node2]

TASK [../roles/nginx : Copy a "sudoers" file on the remote machine] ************
ok: [local]
fatal: [node2 -> local]: FAILED! => {"changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node2:/config/nginx/", "msg": "ssh: Could not resolve hostname node2: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}
fatal: [node1 -> local]: FAILED! => {"changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node1:/config/nginx/", "msg": "ssh: Could not resolve hostname node1: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}

TASK [../roles/nginx : Start Nginx load balancer] ******************************
fatal: [local]: FAILED! => {"changed": false, "msg": "Error starting container 5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156: 400 Client Error for http+docker://localhost/v1.42/containers/5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/nginx/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/nginx/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}

PLAY RECAP *********************************************************************
local                      : ok=5    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node1]
ok: [node2]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node2]
ok: [node1]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy config file to dirs on host] ***********************
skipping: [local]
skipping: [node1]
skipping: [node2]

TASK [../roles/nginx : Copy a config file on the remote machine] ***************
ok: [local]
fatal: [node2 -> local]: FAILED! => {"changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node2:/config/nginx/", "msg": "ssh: Could not resolve hostname node2: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}
fatal: [node1 -> local]: FAILED! => {"changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node1:/config/nginx/", "msg": "ssh: Could not resolve hostname node1: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}

TASK [../roles/nginx : Start Nginx load balancer] ******************************
fatal: [local]: FAILED! => {"changed": false, "msg": "Error starting container 5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156: 400 Client Error for http+docker://localhost/v1.42/containers/5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/nginx/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/nginx/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}

PLAY RECAP *********************************************************************
local                      : ok=5    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   


PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [local]
ok: [node2]
ok: [node1]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/config.yml for local, node1, node2

TASK [../roles/nginx : Check docker install.] **********************************
ok: [node1]
ok: [node2]
ok: [local]

TASK [../roles/nginx : include_tasks] ******************************************
included: /home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/tasks/service.yml for local, node1, node2

TASK [../roles/nginx : Copy config file to dirs on host] ***********************
skipping: [local]
skipping: [node1]
skipping: [node2]

TASK [../roles/nginx : Copy a config file on the remote machine] ***************
changed: [local]
fatal: [node1 -> local]: FAILED! => {"changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node1:/config/", "msg": "ssh: Could not resolve hostname node1: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}
fatal: [node2 -> local]: FAILED! => {"changed": false, "cmd": "sshpass -d4 /usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' '/home/ubuntu/Viettel-Digital-Talent-2023/Midterm/Tran Duc Manh/roles/nginx/files' ubuntu@node2:/config/", "msg": "ssh: Could not resolve hostname node2: Temporary failure in name resolution\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]\n", "rc": 255}

TASK [../roles/nginx : Start Nginx load balancer] ******************************
fatal: [local]: FAILED! => {"changed": false, "msg": "Error starting container 5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156: 400 Client Error for http+docker://localhost/v1.42/containers/5ae18c87bae694170a972b04adc226caead6262f12a5ebf8414b299a681b5156/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/config/nginx/api.conf\" to rootfs at \"/etc/nginx/conf.d/default.conf\": mount /config/nginx/api.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}

PLAY RECAP *********************************************************************
local                      : ok=5    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
node1                      : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
node2                      : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

